services:
  app:
    build: ./app
    container_name: web-app
    hostname: web-app
    volumes: ["./app/src:/appcode"]
    ports:
      - 8501:8501

  api:
    build: ./api
    container_name: web-api
    hostname: web-api
    volumes: ["./api:/apicode"]
    ports:
      - 4000:4000

  db:
    image: mysql:9
    env_file:
      - ./api/.env
    environment:
      - MYSQL_DATABASE=weight-a-minute
    container_name: mysql_db
    hostname: db
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3200:3306

  data-loader:
    image: python:3.9-slim
    container_name: data-loader
    depends_on:
      - db
    env_file:
      - ./api/.env
    volumes:
      - ./database-files:/app
    command: >
      bash -c "
        pip install pandas sqlalchemy pymysql python-dotenv cryptography &&
        python /app/02_insert_data.py
      "