name: project-app-testing
services:
  app-test:
    build: ./app
    container_name: web-app-test
    hostname: web-app
    volumes: ["./app/src:/appcode"]
    ports:
      - 8502:8501

  api-test:
    build: ./api
    container_name: web-api-test
    hostname: web-api
    volumes: ["./api:/apicode"]
    ports:
      - 4001:4000

  db-test:
    image: mysql:9
    env_file:
      - ./api/.env
    environment:
      - MYSQL_DATABASE=weight-a-minute
    container_name: mysql-db-test
    hostname: db
    volumes:
      - ./database-files:/docker-entrypoint-initdb.d/:ro
    ports:
      - 3201:3306

  data-loader-test:
    image: python:3.9-slim
    container_name: data-loader
    depends_on:
      - db
    env_file:
      - ./api/.env
    volumes:
      - ./database-files:/app:ro
    command: >
      bash -c "
        pip install pandas sqlalchemy pymysql python-dotenv &&
        python /app/02_insert_data.py
      "

